Update mysql_cicd.yml

diff --git a/.github/workflows/mysql_cicd.yml b/.github/workflows/mysql_cicd.yml
--- a/.github/workflows/mysql_cicd.yml
+++ b/.github/workflows/mysql_cicd.yml
@@ -3,88 +3,83 @@ name: Database Migration
 on: 
   push:
     branches: 
-      - main
+      - mysql_cicd_update1
+ #   paths:
+ #     - '/dbscripts/deploy/**'
 
 jobs:
   migrate:
     runs-on: ubuntu-latest
 
-    services:
-      mysql:
-        image: mysql:8.0
-        ports:
-          - 3306:3306
-        env:
-          MYSQL_ROOT_PASSWORD: rootpassword
-          MYSQL_USER: testuser
-          MYSQL_PASSWORD: testpassword
-        options: >-
-          --name mysql-db
-          --health-cmd="mysqladmin ping --silent"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=3
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Create Docker network
+      run: docker network create my-network
+
+    - name: Start MySQL service
+      run: |
+        docker run -d \
+          --name mysql-db \
+          --network my-network \
+          -e MYSQL_ROOT_PASSWORD=rootpassword \
+          -e MYSQL_USER=testuser \
+          -e MYSQL_PASSWORD=testpassword \
+          -p 3306:3306 \
+          mysql:8.0 \
+
+
     - name: Wait for MySQL to be ready
       run: |
-        for i in {30..0}; do
-          if docker exec mysql-db mysql -u testuser -ptestpassword -e "SELECT 1" > /dev/null 2>&1; then
+        for i in {180..0}; do
+          if docker exec mysql-db mysql -u root -prootpassword -e "SELECT 1" > /dev/null 2>&1; then
+            echo 'MySQL is connecting'
             break
           fi
           echo 'MySQL not ready yet...'
           sleep 1
         done
-    
+
     - name: Initialize Database Schemas and Grant Permissions
-      run: |
-        docker exec -i mysql-db mysql -u root -prootpassword < $GITHUB_WORKSPACE/init.sql
-    - name: Display All Databases and Users Table Schema
-      run: |
-        echo "Listing all databases and 'users' table schema for each database:"
-        for db in schema1 schema2 schema3 schema4 schema5 schema6 schema7 schema8 schema9 schema10; do
-            echo "Checking database: $db"
-            docker exec -i mysql-db mysql -u testuser -ptestpassword -e "USE $db; SHOW CREATE TABLE users;"
-        done    
-    - name: Ceating docker network
-      run: |
-         docker network create my-network
-         
-    - name: Download MySQL JDBC Driver
-      run: |
-        curl -L -o mysql-connector-java.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.32/mysql-connector-java-8.0.32.jar
-        ls -l mysql-connector-java.jar
-        
-        
-    - name: Run Liquibase migrations
-      run: |
-        LIQUIBASE_IMAGE="ashwinsirigi/liquibase-mysql-driver"
-        CHANGELOG_FILE="/liquibase/changelog/change.sql"
-        #docker inspect mysql-db | grep '"IPAddress": ' 
-        docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql-db
-        #dockerhost=$(docker inspect mysql-db | grep '"IPAddress": ' | cut -d':' -f2 | tr -d ' ' | tr -d "," |tr  -d '"' | head -n 1)
-        dockerhost=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql-db)
-        echo $dockerhost
-        URL_PREFIX="jdbc:mysql://my-network:3306/schema1"
-        echo $URL_PREFIX
-        LIQUIBASE_LICENSEKEY="ABwwGgQUDvg+TwPk6F7EmjJg6gLEDLZj3OwCAgQAJJ5Jc0vNRRNw2+eZgro/35pG6BZu+MvhRd+vS9n5TzBhC0NcrYT8iO6BB90jcxfL/0mm0OIMe+Pxav/1lw9DjQo7b6Ubf5rnXo9yFnm2Szo8E2+A5x/Fdgg57ah2OGQFVJUD1kNrHNTSxeu0UN2yevASADRTfgiSC1FPo32X/B3LSr29ItF0qsTSbFONdbOFASSaAxI9ZAsIEG18WfZfSNMn0N7lRdRpQekxjGngepZiBY0S5I4lkL3mCikbWk8R7KfmATWUvVXpNP8tbSPCbAe/vRrgdX4QyakARO+jwddwinlMoF6afkBTDJ3OqQ9jFOMFeCb9EJPI608mlHjYVytQgQ1kwsEkdjM1lT+Dz8mtXc/XBagHFrgxutAVZrjQB7MxqasiLNpJEExO80oy6QWaEkTuMSjx29sfU77OYNV9GBUZ1iA3fny1lq98cMYGj1f57tJr8JFFZ/di8V0QJdx7t/7t3JjFPEFuubPGuv3RU47eR/MdFsi57H8dBxmaQQqxlNyxBilUUXWEm0E87gERv4QHgNh1g+RGXhcWN6YaQqFHyaufw0F1VGmDsgKK/C7drQdrXHC5HxCL5wQs2xhIdcDtZYW8goF7oud/cuJklq/YotaU+EEGoFYewGcOSSi7P1PlWnvgHvQkye7gh0W6dblgSoJv"
-        DB_DRIVER="com.mysql.cj.jdbc.Driver"
-        
-        docker run --rm --network my-network -v $GITHUB_WORKSPACE/dbscripts:/liquibase/changelog -v $(pwd)/mysql-connector-java.jar:/liquibase/lib/mysql-connector-java.jar $LIQUIBASE_IMAGE \
-          --changeLogFile=${CHANGELOG_FILE} \
-          --url="${URL_PREFIX}" \
-          --username=testuser \
-          --password=testpassword \
-          --classpath=/liquibase/lib/mysql-connector-java.jar \
-          --license-key=${LIQUIBASE_LICENSEKEY} \
-          --driver=${DB_DRIVER} \
-          connect
+      run: docker exec -i mysql-db mysql -u root -prootpassword < $GITHUB_WORKSPACE/init.sql; 
+       echo "Database Restoration Completed"
+
     - name: Display All Databases and Users Table Schema
       run: |
         echo "Listing all databases and 'users' table schema for each database:"
         for db in schema1 schema2 schema3 schema4 schema5 schema6 schema7 schema8 schema9 schema10; do
           echo "Checking database: $db"
           docker exec -i mysql-db mysql -u testuser -ptestpassword -e "USE $db; SHOW CREATE TABLE users;"
-        done
+        done    
+
+    - name: Verify change.sql file exists
+      run: |
+        if [ ! -f "$GITHUB_WORKSPACE/dbscripts/change.sql" ]; then
+          echo "change.sql file not found!"
+          exit 1
+        else
+          echo "change.sql file exists $GITHUB_WORKSPACE/dbscripts/change.sql"
+        fi      
+        
+    - name: Run Liquibase connection test
+      run: |
+        LIQUIBASE_IMAGE="liquibase/liquibase"
+        CHANGELOG_FILE="masterChangeLog.xml"
+        URL_PREFIX="jdbc:mysql://mysql-db:3306/schema1"
+        LIQUIBASE_LICENSEKEY="ABwwGgQUDvg+TwPk6F7EmjJg6gLEDLZj3OwCAgQAJJ5Jc0vNRRNw2+eZgro/35pG6BZu+MvhRd+vS9n5TzBhC0NcrYT8iO6BB90jcxfL/0mm0OIMe+Pxav/1lw9DjQo7b6Ubf5rnXo9yFnm2Szo8E2+A5x/Fdgg57ah2OGQFVJUD1kNrHNTSxeu0UN2yevASADRTfgiSC1FPo32X/B3LSr29ItF0qsTSbFONdbOFASSaAxI9ZAsIEG18WfZfSNMn0N7lRdRpQekxjGngepZiBY0S5I4lkL3mCikbWk8R7KfmATWUvVXpNP8tbSPCbAe/vRrgdX4QyakARO+jwddwinlMoF6afkBTDJ3OqQ9jFOMFeCb9EJPI608mlHjYVytQgQ1kwsEkdjM1lT+Dz8mtXc/XBagHFrgxutAVZrjQB7MxqasiLNpJEExO80oy6QWaEkTuMSjx29sfU77OYNV9GBUZ1iA3fny1lq98cMYGj1f57tJr8JFFZ/di8V0QJdx7t/7t3JjFPEFuubPGuv3RU47eR/MdFsi57H8dBxmaQQqxlNyxBilUUXWEm0E87gERv4QHgNh1g+RGXhcWN6YaQqFHyaufw0F1VGmDsgKK/C7drQdrXHC5HxCL5wQs2xhIdcDtZYW8goF7oud/cuJklq/YotaU+EEGoFYewGcOSSi7P1PlWnvgHvQkye7gh0W6dblgSoJv"
+        DB_DRIVER="com.mysql.cj.jdbc.Driver"
+        
+        docker run  -e INSTALL_MYSQL=true --rm --network my-network \
+        -v $GITHUB_WORKSPACE/dbscripts:/liquibase/changelog \
+        -v $GITHUB_WORKSPACE/masterChangeLog.xml:/liquibase/changelog.xml \
+        -v $(pwd)/mysql-connector-java.jar:/liquibase/lib/mysql-connector-java.jar $LIQUIBASE_IMAGE \
+          --changeLogFile=${CHANGELOG_FILE} \
+          --url="${URL_PREFIX}" \
+          --username=root \
+          --password=rootpassword \
+          --classpath=/liquibase/lib/mysql-connector-java.jar \
+          --license-key=${LIQUIBASE_LICENSEKEY} \
+          status
+
+        
